-- Synodos 데이터베이스 리셋 스크립트
-- 실행 방법: psql -U flow -d synodos -f reset.sql

-- 모든 테이블 삭제
DROP TABLE IF EXISTS member_social_link CASCADE;
DROP TABLE IF EXISTS github_issue_sync_log CASCADE;
DROP TABLE IF EXISTS github_user_mapping CASCADE;
DROP TABLE IF EXISTS task_github_issue CASCADE;
DROP TABLE IF EXISTS email_verification CASCADE;
DROP TABLE IF EXISTS task_verifier CASCADE;
DROP TABLE IF EXISTS task_assignee CASCADE;
DROP TABLE IF EXISTS task_archive CASCADE;
DROP TABLE IF EXISTS task_favorite CASCADE;
DROP TABLE IF EXISTS task_commit CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS chat_message CASCADE;
DROP TABLE IF EXISTS column_assignee CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS file CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS columns CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS team_member CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS member CASCADE;

-- 시퀀스도 삭제
DROP SEQUENCE IF EXISTS member_social_link_seq CASCADE;
DROP SEQUENCE IF EXISTS member_seq CASCADE;
DROP SEQUENCE IF EXISTS team_seq CASCADE;
DROP SEQUENCE IF EXISTS project_seq CASCADE;
DROP SEQUENCE IF EXISTS column_seq CASCADE;
DROP SEQUENCE IF EXISTS task_seq CASCADE;
DROP SEQUENCE IF EXISTS comment_seq CASCADE;
DROP SEQUENCE IF EXISTS chat_seq CASCADE;
DROP SEQUENCE IF EXISTS notification_seq CASCADE;
DROP SEQUENCE IF EXISTS file_seq CASCADE;
DROP SEQUENCE IF EXISTS email_verification_seq CASCADE;
DROP SEQUENCE IF EXISTS task_archive_seq CASCADE;
DROP SEQUENCE IF EXISTS task_commit_seq CASCADE;
DROP SEQUENCE IF EXISTS task_github_issue_seq CASCADE;
DROP SEQUENCE IF EXISTS github_user_mapping_seq CASCADE;
DROP SEQUENCE IF EXISTS github_issue_sync_log_seq CASCADE;

-- Done
